***Importing library and loading dataset "trends.csv"***

In [1]:
import pandas as pd
dataframe=pd.read_csv("/content/trends.csv")

***featching first five row of dataset***

In [2]:
dataframe.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

***Featching last five rows of dataset***

In [3]:
dataframe.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

***printing shape of dataset***

In [4]:
dataframe.shape

(26955, 5)

***featching metadata about columns***

In [5]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  object
 1   year      26955 non-null  int64
 2   category  26955 non-null  object
 3   rank      26955 non-null  int64
 4   query     26955 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.0+ MB

***featching statical information of data***

In [15]:
dataframe.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

***featching columns name of dataframe***

In [7]:
dataframe.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='object')

***Featching datatype of each column of dataset***

In [8]:
dataframe.dtypes

location    object
year         int64
category    object
rank         int64
query       object
dtype: object

***featching null values count in the columns***

In [9]:
dataframe.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

***featching the sum of duplicate values in dataframe***

In [10]:
dataframe.duplicated().sum()

np.int64(10)

In [21]:
dataframe.drop_duplicates(inplace=True)

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26945 rows x 5 columns]

***featching the count of unique value in each columns***

In [11]:
dataframe.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [32]:
dataframe["year"]=pd.to_datetime(dataframe["year"], format="%Y")

In [33]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  object
 1   year      26955 non-null  datetime64[ns]
 2   category  26955 non-null  object
 3   rank      26955 non-null  int64
 4   query     26955 non-null  object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.0+ MB